# This is the name of the workflow. It appears in the GitHub Actions tab.
name: Deploy Application

# 'on' specifies the event that triggers the workflow.
on: 
  push:              # Trigger the workflow when a push occurs
    branches:        # Specify the branches to listen to
      - main         # Only run when pushing to the 'main' branch

# 'jobs' define the tasks to be performed.
jobs: 
  deploy:            # Name of the job (you can choose any name)
    runs-on: ubuntu-latest  # The environment to run the job (Ubuntu virtual machine)

    # 'steps' define the sequence of tasks within the job.
    steps:

      - name: pwd
        run: pwd

      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3  # Uses the 'checkout' action to download the code
        with:
          path: ./  # Checkout directly into the root workspace directory

      - name: Removing existing Deployment Directory
        run:  sudo rm -rf /var/www/photogram

      - name: Copying Code to Deployment Directory
        run:  sudo cp -r $(pwd) /var/www/photogram

      - name: Removing .git Directory
        run: |
          rm -rf /var/www/photogram/htdocs/.git

      - name: Verify Deployment Directory
        run: ls -la /var/www/photogram
     











