# This is the name of the workflow. It appears in the GitHub Actions tab.
name: Deploy Application

# 'on' specifies the event that triggers the workflow.
on: 
  push:              # Trigger the workflow when a push occurs
    branches:        # Specify the branches to listen to
      - main         # Only run when pushing to the 'main' branch

# 'jobs' define the tasks to be performed.
jobs: 
  deploy:            # Name of the job (you can choose any name)
    runs-on: ubuntu-latest  # The environment to run the job (Ubuntu virtual machine)

    # 'steps' define the sequence of tasks within the job.
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3  # Uses the 'checkout' action to download the code
     
      - name: Create index.html
        run: |
          echo '<!DOCTYPE html>' > /var/www/photogram/index.html
          echo '<html lang="en">' >> /var/www/photogram/index.html
          echo '<head>' >> /var/www/photogram/index.html
          echo '  <meta charset="UTF-8">' >> /var/www/photogram/index.html
          echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> /var/www/photogram/index.html
          echo '  <title>Welcome to Photogram</title>' >> /var/www/photogram/index.html
          echo '</head>' >> /var/www/photogram/index.html
          echo '<body>' >> /var/www/photogram/index.html
          echo '  <h1>Hello, Photogram!</h1>' >> /var/www/photogram/index.html
          echo '  <p>This is a simple index page created by the pipeline.</p>' >> /var/www/photogram/index.html
          echo '</body>' >> /var/www/photogram/index.html
          echo '</html>' >> /var/www/photogram/index.html

      - name: Verify index.html creation
        run: cat /var/www/photogram/index.html
     











