# This is the name of the workflow. It appears in the GitHub Actions tab.
name: Deploy to Production

# 'on' specifies the event that triggers the workflow. 
on:
  push:             # Trigger the workflow when a push occurs
    branches:       # Specify the branches to listen to
      - main        # Only run when pushing to the 'main' branch

# 'jobs' define the tasks to be performed.
jobs:
  deploy:           # Name of the job (you can choose any name)
    runs-on: ubuntu-latest      # The environment to run the job (Ubuntu virtual machine)

    # 'steps' define the sequence of tasks within the job.
    steps:

      - name: pwd
        run: pwd

      - name: Checkout code
        uses: actions/checkout@v4     # Uses the 'checkout' action to download the code

      - name: Setup SSH               # Set up SSH with the private key from GitHub Secrets
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}      # Development server private key

      # SSH into the production server and pull the latest code
      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.127.103.213 'cd /var/www/photogram && git pull origin main' 

      - name: Removing .git Directory
        run: |
          rm -rf /var/www/photogram/htdocs/.git

      - name: Verify Deployment Directory
        run: sudo ls -la /var/www/photogram/
      













