# This is the name of the workflow. It appears in the GitHub Actions tab.
name: Deploy Application

# 'on' specifies the event that triggers the workflow.
on: 
  push:              # Trigger the workflow when a push occurs
    branches:        # Specify the branches to listen to
      - main         # Only run when pushing to the 'main' branch

# 'jobs' define the tasks to be performed.
jobs: 
  deploy:            # Name of the job (you can choose any name)
    runs-on: ubuntu-latest  # The environment to run the job (Ubuntu virtual machine)

    # 'steps' define the sequence of tasks within the job.
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3  # Uses the 'checkout' action to download the code
      
      - name: whoami
        run: whoami
        
      - name: Delete .git Folder
        run: sudo rm -rf /var/www/photogram/.git

